porn-vault/porn-vault

src/extractor.ts
src/graphql/mutations/actor.ts
src/graphql/mutations/label.ts
src/graphql/mutations/studio.ts
src/queue/index.ts

Improve matching algorithm by stripping and ignoring all whitespaces for actors/labels/studio
Also fixed queue/index.ts processLoop
Previously, if we have "Actor Name" (with a space between words), it wouldn't match a filename called xxxActorNamexxx. Now it would.
This would fix https://github.com/boi123212321/porn-manager/issues/198 and a bug introduced by https://github.com/boi123212321/porn-manager/issues/189

Improve matching by ignoring spaces & Fix processLoop

---

app/src/components/ActorGrid.vue
app/src/views/SceneDetails.vue

The age of the performer is calculated with the release date of the scene. So the calculated age is the exact difference to the release date. This is a suggestion for #404 
I've added a text field containing the calculated age when hovering over the actor card. If the scene has no release date or the actor has no birth date, the age will not be calculated. 
**Example**: 
Katana Kombat has a birth date set and the scene has a release date. The paragraph with her age in this scene will be shown on the actor card. (Note: I've replaced her profile picture with the green background).
**Example No. 2**: 
John Doe has no birth date set and because of that, his age will not be calculated and not be shown.

added age calculation for performer in scene

---

src/plugin_events/actor.ts

Discovered this project a few weeks ago and love using it. Adding some more love here.
The changes allow actor plugins to set and persist hero, altThumbnail and avatar images.
A plugin that takes advantage of this change to populate actor images and aliases [is also submitted in a pull request](https://github.com/boi123212321/porn-manager-plugins/pull/1/).

Support for actor plugins to add images

---

README.md

When viewing the Readme from somewhere else than Github (example Docker Hub), the images will not be displayed
This PR changes the URLs of the images to static ones so that they can be retrieved from anywhere.

[Docs] Replace relative image links with static ones

---

Dockerfile

The flags weren't showing up when built with Docker, because the assets folder was not copied to the container

fix(Dockerfile): copy assets to container

---

doc/build_from_source.md

Added line in build_from_source.md documentation to include missing step.

Build from Source doc now includes Transpile step

---

app/src/components/SceneCard.vue
app/src/store/context.ts
app/src/views/About.vue

I have added an option to toggle the scene preview when hovering over a SceneCard. This option can be toggled in the "About" section. This PR can be seen as enhancement to #454.

Toggle option for scene preview in SceneCard

---

test/config/index.spec.ts
test/config/schema.fixture.ts
test/config/schema.spec.ts

- remove tests: auto insertion of missing config key
- add tests: process does not exit/exists if valid/invalid config
- add tests: config schema validator returns correct values for valid/invalid config

New Config: add tests

---

.eslintignore
package.json

- the glob for spec files was expanded on execution of the command, instead of passing the glob to mocha

fix(tests): test file glob

---

app/src/components/DateInput.vue

I have added a date-picker inside of the DateInput component. The datepicker becomes visible when clicking on the calender icon left of the text field. The date can still be typed in by hand.

feature/enhancement: Datepicker in DateInput component

---

src/graphql/mutations/image.ts
src/graphql/mutations/scene.ts
src/types/actor.ts
src/types/custom_field.ts
src/types/image.ts
src/types/label.ts
src/types/marker.ts
src/types/movie.ts
src/types/scene.ts
src/types/studio.ts

- Replaces: from an array of ids, search each id individually, to map the results back to an array. Now: from an array of ids, search for all the ids in bulk
- As a byproduct, this greatly reduces the delay when searching for scenes in the web app, and building the image index on server startup. Other areas may also be sped up
- Examples: db with 7k scenes, 761 labels (localhost)
- - Search for scenes: ~1250ms to ~250ms
- - Image index build: ~250s to ~100s

refactor(getById): use getBulk when possible

---

app/src/components/VideoPlayer.vue
package-lock.json

- Centers the video vertically in the wrapper
- - Shouldn't change for 16:9 screens, but fixes for taller ones
- - Should fix #825 but I don't have an iPad, so this is just from simulating with Chrome 
- Fits the video height to the wrapper height.
- - On wider screens, the video would fit the width, and thus the top and bottom would be cut off
- - In the future, this could be a button in the player UI: to fit width or height (created #828)

Fix: video player white background on tall screens

---

doc/guides.md

Link to the bulk import doc page is broken, this should fix it.

Fixed broken link to the bulk import doc page

---

app/src/components/ImageCard.vue
app/src/views/Images.vue

- Enable ctrl/shift selection to toggle selection states, when clicking **anywhere** on an image. Images can still be opened, when clicking anywhere except the checkbox, with ctrl/shift **not** held down.
- - Shift selection, will apply opposite state of the clicked image's current state, from the last clicked image (or the current clicked image, if no previous) to the current clicked image
- Always show selection banner.
- - Add 'Select all' button
Closes #482

refactor(Images): ctrl/shift selection

---

src/types/scene.ts
src/utils/misc.ts
test/utils/misc.fixtures.ts
test/utils/misc.spec.ts

- use timestamps in seconds, for generating previews & thumbnails
- - This should barely affect local files (since the durations are so short). But it will
be more noticeable on remote files, where the durations are longer.
Tested against preview generation:

refactor(scene): use seconds for timestamps in thumbnail generation

---

src/plugins/index.ts

- `ts-node` uses a dynamic require to `typescript`, so `pkg` won't include it in the bundle. We can force pkg to include it, by simply importing it

hotfix(plugins): import typescript

---

src/utils/fs/async.ts
test/walk.spec.ts

- ignore dotfiles
- stop walk after first truthy value from callback (like Array.find)

adjust $walk

---

src/graphql/mutations/image.ts
src/matching/wordMatcher.ts
src/utils/fs/async.ts
src/utils/string.ts
test/utils/fixtures/get_extension.fixture.ts
test/utils/fixtures/remove_extension.fixture.ts
test/utils/string.spec.ts

> Cant seem to set a alt thumbnail image. Can pick a file, choose the cropping area but when I set the viewport just refreshes and does not set the image.  In the console you get the lines:
vault:success File written to tmp/im_khwdkgazyspWZe85.jpg. +0ms
vault:success Image processing done. +0ms
but it's not followed by "vault:success Image 'Actor Name (alt thumb)' done." line like it does for setting any other image.
When setting any of the other image types the viewport closes after cropping the image but it does not show the updated image in the 'change actor images' dialogue until after a refresh.

fix: cannot set actor alt thumbnail

---

doc/config.md
doc/docker.md
doc/env.md
doc/guides.md
doc/startup_options.md
docker/Dockerfile.alpine
docker/Dockerfile.debian
src/middlewares/apollo.ts
src/utils/path.ts

- Closes #1192
- Closes #1191 as a side effect
- Removes docker detection, in favor of environment variable: `PV_CONFIG_FOLDER`
- Rename `QL_PLAYGROUND` to `PV_QL_PLAYGROUND`

fix: use env variable for config folder

---

src/queue_loop.ts
src/types/scene.ts

- Fixes #1316 only for future generated thumbnails
The generated thumbnail path was found by searching for a file containing the scene id. The problem was that it would find the first generated screenshot since those files also contain the scene id.

Fix scene thumbnail/screenshot name conflict

---

app/src/App.vue
app/src/router/index.ts

Closes #1274
- Enable the active status of the main app bar when navigating from a route where it was hidden to a route where it shouldn't
- Move the details app bar definition to the route's meta. Each route can simply add it's own app bar component in the meta. When the route is active:
- - the details app bar will automatically be rendered in App
- - the main app bar will be hidden on scroll

fix: app bar would disappear when navigating backwards

---

src/server.ts

We only need to backup right before loading the db. Before, when pv would quit because izzy/elasticsearch weren't running, and with automatic restarts, a large amount of useless backups could be created

fix(server): only backup before loading db

---

.github/workflows/build-server.yml
src/transcode/mp4.ts
test/testServer.ts
test/transcode/mp4.spec.ts

- Drivers other than amf may not support bitrate options, so the ffmpeg transcode will fail. So far, we only know that amf on windows requires bitrate options. We can do more research if we ever want user selectable bitrates.
- Don't apply hardware encoder when the stream is already mp4 compatible

fix(mp4 transcode): only apply bitrate for amf windows

---

docker/Dockerfile.debian
docker/root/etc/cont-init.d/40-init-dirs
docker/root/etc/cont-init.d/50-gid-video
docker/root/etc/services.d/porn-vault/finish
docker/root/etc/services.d/porn-vault/run

- Run porn-vault via an s6 service with the correct user
- Fixes files being created as `root` instead of the user defined by `PUID, PGID`

refactor(docker): use s6 service
