app/src/components/QueueInfo.vue, app/src/components/SceneCard.vue, app/src/components/SceneUploader.vue, app/src/router/index.ts, app/src/views/About.vue, app/src/views/SceneDetails.vue, package-lock.json, package.json, src/config/index.ts, src/database/index.ts, src/fs/async.ts, src/graphql/mutations/image.ts, src/graphql/mutations/scene.ts, src/graphql/resolvers/query.ts, src/graphql/types.ts, src/hash.ts, src/logger/index.ts, src/queue/check.ts, src/queue/index.ts, src/server.ts, src/setup.ts, src/types/image.ts, src/types/scene.ts
+ formatted config.json
+ use absolute paths
=> Bulk import of folders, async queue worker

src/version.ts
=> Fixed version

app/src/views/SceneDetails.vue
=> Fix auto resume

app/src/components/VideoPlayer.vue
I've added an audio mute button to the VideoPlayer component.
Muted: 
Unmuted:
=> added mute button to VideoPlayer component

app/package-lock.json, app/package.json, app/src/App.vue, app/src/components/ActorGrid.vue, app/src/components/SceneSelector.vue, app/src/components/SearchIndexInfo.vue, app/src/router/index.ts, app/src/views/ActorDetails.vue, app/src/views/Graph.vue, app/src/views/Home.vue, nodemon.json, package-lock.json, package.json, src/config/index.ts, src/graphql/mutations/image.ts, src/graphql/resolvers/actor.ts, src/graphql/resolvers/query.ts, src/graphql/resolvers/studio.ts, src/graphql/schema/actor.ts, src/graphql/schema/index.ts, src/graphql/schema/scene.ts, src/queue/check.ts, src/search/index.ts, src/server.ts, src/types/actor.ts, src/types/scene.ts, src/types/utility.ts
=> 0.15.0-rc.5

app/src/App.vue
Title says it all. It's currently painful on mobile to go back to the Home page. This PR adds the home button back for easy navigation.
=> Added Home button to hamburger menu

README.md, src/config/index.ts, src/server.ts
Documentation for this feature can be found in the README
=> Add an option to enable HTTPS, closes #463

app/src/App.vue, app/src/components/AppBar/StudioDetails.vue, app/src/store/actor.ts, app/src/views/ActorDetails.vue, app/src/views/Actors.vue, app/src/views/Images.vue, app/src/views/Movies.vue, app/src/views/SceneDetails.vue, app/src/views/Scenes.vue, app/src/views/StudioDetails.vue, app/src/views/Studios.vue, src/extractor.ts, src/graphql/mutations/actor.ts, src/graphql/mutations/label.ts, src/graphql/resolvers/query.ts, src/graphql/schema/label.ts, test/matching_actor.fixture.ts, test/matching_label.fixture.ts, test/string.spec.ts
- #377
- #373
- refactor actor image management (#415 related)
- Fix label filter behavior
- Fix studio not showing up in scene details
=> 0.20.0-rc.6

README.md, doc/docker.md
This PR adds instructions in the Readme on how to run the app with DOcker
=> chore(readme): add docker instructions

.mocharc.js, src/index.ts
Fixes #564 
Thanks to @boi123212321
=> fix(index): don't overload exit when testing

README.md, app/src/components/AppBar/ActorDetails.vue, app/src/components/ImageCard.vue, app/src/views/ActorDetails.vue, run.sh
Fixed PR for https://github.com/boi123212321/porn-vault/pull/558
=> Add ability to use existing actor images as thumbnail, alt, hero

app/src/components/VideoPlayer.vue
* allows users to set sound, not only mute and unmute like previously
* persists sound (muted and volume) settings in localStorage
* applies settings from localStorage in mounted(), this way they are applied even when the video is started from fullscreen
* draggable
=> added bar in player to change volume

app/package-lock.json, app/package.json, app/src/components/HomeWidgets/ActorLabelUsage.vue, app/src/components/HomeWidgets/SceneLabelUsage.vue, app/src/components/HomeWidgets/SearchTimes.vue, app/src/views/Views.vue
- Charts would be initialized before the canvas was rendered, causing an error
- Added chart cleanup, some console error logging
=> Fix dashboard charts: charts would not be shown

app/src/components/SceneCard.vue
- Show a "WATCHED" chip in the top left of a scene card, when it has at least 1 watch
=> Enhancement(SceneCard): add watched chip

app/src/views/Markers.vue
=> fix(Markers): update refresh on sort change

app/src/components/ActorSelector.vue, app/src/components/SceneSelector.vue, app/src/components/StudioSelector.vue, app/src/views/ActorDetails.vue, app/src/views/MovieDetails.vue, app/src/views/SceneDetails.vue
- Forgot to update usage of ImageCard in #829 
- Closes #905 
- Update query format in Selector components
=> fix(ImageCard): use click event, search query format

src/config/index.ts, src/config/validate.ts, src/index.ts, src/utils/logger.ts, test/config/index.spec.ts, test/plugins/fixtures/config.test.fixture_js.json, test/plugins/fixtures/config.test.fixture_ts.json, test/plugins/initPluginFixtures.ts
- remove circular import
- cleanup config validation, reload
- add more tests
=> refactor config: clean

app/src/components/SceneSelector.vue, app/src/views/Images.vue
=> Fix scene selector: update scenes

src/graphql/mutations/movie.ts
=> fix(movie mutation): return updated movies

app/src/views/Scenes.vue
- ~~change the default max duration from 180 to 181. When the user changes the start/end of the range to 181, that  start/end will not be sent~~
- Since the default end range is the max, the default will now be unlimited duration
- Closes #1000
=> refactor(Scenes): allow unlimited duration

app/src/views/SceneDetails.vue
=> fix(SceneDetails): don't trigger with kb modifiers

app/src/views/ActorDetails.vue, app/src/views/SceneDetails.vue, app/src/views/StudioDetails.vue, src/graphql/mutations/studio.ts, src/graphql/schema/studio.ts
- remove `runAllStudioPlugins`
- update scene, actor, studio plugin mutations to receive a single id, output single result
=> fix: scene & actor plugins can't be run from web ui

src/plugins/context.ts, src/plugins/events/actor.ts, src/plugins/events/movie.ts, src/plugins/events/scene.ts, src/plugins/events/studio.ts, src/search/index.ts, src/types/actor.ts, src/types/image.ts, test/plugins/events/actor.spec.ts, test/plugins/events/scene.spec.ts, test/plugins/events/studio.spec.ts, test/plugins/fixtures/actor_plugin.fixture.js, test/plugins/fixtures/movie_plugin.fixture.js, test/plugins/fixtures/scene_plugin.fixture.js, test/plugins/fixtures/studio_plugin.fixture.js
=> allow plugins to use existing local images with $createLocalImage

src/plugins/index.ts
- zod was not imported correctly
=> fix: plugins could not use $zod

app/src/views/ActorDetails.vue
=> fix(ActorDetails): refresh linked data after attaching

app/src/components/HomeWidgets/Stats.vue
this card data was just being updated when we refresh the page.
=> add a refresh interval on home stats card

src/extractor.ts
=> Fix: match custom field with legacy matcher

app/src/views/ActorDetails.vue, src/types/actor.ts
- return 0 score when actor has 0 scenes
- request score,averageRating for all actor operations in ActorDetails
=> fix calculateScore, retrieve score on actor details page

src/plugins/events/scene.ts
=> fix(scene plugin events): check matchCreatedActors

nodemon.json, src/utils/logger.ts
=> fix(createFileTransport): deterministic auditFile

src/extractor.ts, src/graphql/mutations/label.ts, src/types/actor.ts, src/types/studio.ts, test/graphql/mutations/label.spec.ts
=> AddLabel: only match created label

src/search/actor.ts, src/search/image.ts, src/search/marker.ts, src/search/movie.ts, src/search/scene.ts, src/search/studio.ts, test/graphql/mutations/movie.spec.ts
=> Fix: could not delete movie

src/middlewares/apollo.ts
=> Feat: log apollo errors

src/queue_loop.ts
=> fix: processing would fail when using a self-signed certificate

app/src/components/ActorSelector.vue, app/src/components/StudioSelector.vue
Closes #430
Shows all aliases and not just "the alias that may have been "hit" as part of the query"
=> Feat: show aliases in actor, studio selector

app/src/components/VideoPlayer.vue, app/src/types/scene.ts, app/src/views/MovieDetails.vue, app/src/views/SceneDetails.vue, src/graphql/resolvers/scene.ts, src/queue_loop.ts
- Close #1377
- Scene Details: add studio name fallback when missing logo
=> Fix: preview would show two images at once ; show studio, movie name fallback in details page

app/src/components/VideoPlayer.vue
- seeking wouldn't work with touch
- toggling the controls wouldn't work with touch
=> Fix VideoPlayer: touch problems

app/src/components/VideoPlayer.vue
- preview window would not update position when hovering
- scrubbing would toggle play, when the mouse was released outside the window, but on the video
- preview window would overflow the video bounds
- Enhancement: add seek bar
=> Various VideoPlayer fixes

src/extractor.ts, src/matching/matcher.ts, src/matching/stringMatcher.ts, src/matching/wordMatcher.ts, test/matching/studio.spec.ts
=> Fix studio matching: use last appearance

app/src/views/Scenes.vue, src/graphql/schema/scene.ts, src/search/common.ts, src/search/scene.ts
Refs https://github.com/porn-vault/porn-vault/issues/1701
=> Added possibility to filter unwatched scenes

app/src/components/AppBar/StudioDetails.vue, app/src/fragments/studio.ts, app/src/store/studio.ts, app/src/views/StudioDetails.vue, src/graphql/mutations/studio.ts, src/graphql/schema/studio.ts, src/types/studio.ts
Refs https://github.com/porn-vault/porn-vault/issues/1704
=> Added studio url property
